language: node_js
node_js:
- 0.8
before_script:
- gem install jekyll
- npm install -g grunt-cli
env:
  global:
  - secure: YWGZCUR1R9P40bt/6kRBUyfhc9Er7lynm5tYVtyS/Egoud7l9oMMNQwTzHyhe8XMLxcVZItDiQFqPtQCKtiEnFQo2jknV6U6qAjkD/g1+UKNK+LIouarnKXK7nzV9WVL2Nu14YCZo0D0PmG6Cs6BLOu3mnMgRNtX7fYBPqRRKW4=
  - secure: ONCj+JohcKx3eTpwA4DxHix3gVz+wZwqO8i6zQAr6XtOGxcgJ4xSi1PSHOYw9Lfc5Y4ZD08umlRkYgcbpex9xs7nJFWgv78FWi2xf4+ZlrdB6G7RS6eivitLs3BgxYnIb+g1gvc7S+N8OrKjJszeefl/WcZksb7w2Lwz8pI1138=
  - TWBS_HAVE_OWN_BROWSERSTACK_KEY: 'true'
